sudo: required

language: node

services:
  - docker

before_install:
- docker pull yanqd0/hugo

script:
  - set -e
  - docker run --rm -v $PWD:/srv/hugo yanqd0/hugo hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  # Our token is set in travis-ci.org dashboard
  github_token: $GITHUB_TOKEN
  target-branch: master
  local_dir: public
  on:
    branch: develop
