sudo: required

language: node

before_install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.59.1/hugo_0.59.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.59.1_Linux-64bit.deb

script:
  - hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  # Our token is set in travis-ci.org dashboard
  github_token: $GITHUB_TOKEN
  target-branch: master
  local_dir: public
  on:
    branch: develop
