watch=true
baseurl = "/"
title = "A-programmer's-cave"
copyright = "Copyright (c) 2018 - present, all rights reserved."
languageCode = "en-US"
canonifyurls = true
paginate = 3
theme = "hugo-dusk"

googleAnalytics = ""
disqusShortname = "aprogrammerscave"

SectionPagesMenu = "main"
canonifyURLs = true
# use Chroma for syntax highlight
pygmentsStyle = "native" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[[menu.footer]]
  name = "Comments Policy"
  weight = -110
  identifier = "comments"
  url = "/comments-policy/"

[author]
  name = "Marco Giordano"

[params.meta]
  keywords = ""
  description = "A-programmer's-cave"

[params]
  #globals
  tocname= "Table of contents:"

  #social
  email = "myemail"
  github = "giordi91"
  #gitlab = "gitlab id"
  twitter = "MarcoG_Rigger"
  #linkedin = "linkedin id"

[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#99cc66"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color
